export const notificationTranslations = {
  en: {
    successfulCollaboration: "successful collaboration",
    greatAchievement: "Great achievement!",
    completedWithImpact: "completed with impact:",
    amazingProgress: "Amazing progress!",
    tasksCompletedOutOf: "tasks completed out of",
    teamEfficiency: "Team Efficiency",
    successfulTeamDelivery: "Successful Team Delivery",
    completedWithinBudget: "completed within budget!",
    greatResourceManagement: "Great resource management!",
    inProgress: "in_progress",
    onTrack: "on_track",
  },
  es: {
    successfulCollaboration: "colaboración exitosa",
    greatAchievement: "¡Gran logro!",
    completedWithImpact: "completado con impacto:",
    amazingProgress: "¡Progreso increíble!",
    tasksCompletedOutOf: "tareas completadas de",
    teamEfficiency: "Eficiencia del Equipo",
    successfulTeamDelivery: "Entrega Exitosa del Equipo",
    completedWithinBudget: "¡completado dentro del presupuesto!",
    greatResourceManagement: "¡Excelente gestión de recursos!",
    inProgress: "en_progreso",
    onTrack: "en_curso",
  },
};
